name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Segunda ação"
        run: |
          echo "Você criou o seu primeiro workflow !!!"
          echo "Parabéns !!!"
      - name: "Script Python"
        run: |
          variavel = "Hello World !!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalação do ambiente Node.js"
    runs-on: ubuntu-latest
    steps:
       - name: "Verificação da versão do Nodejs atual"
         run: node --version
